services:
  - type: web
    name: fallback-products-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
